import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Footer } from '@/components/Footer';
import { ChakraProvider } from '@chakra-ui/react';
import { StoreProvider } from '@/redux/store';
import ProtectedPage from '@/routes/protected-routes';
import AuthProvider from '@/routes/auth-provider';
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          {/* <ChakraProvider> */}
          <AuthProvider>
            <ProtectedPage>
              <Navbar />
              {children}
              <Footer />
            </ProtectedPage>
          </AuthProvider>
          {/* </ChakraProvider> */}
        </body>
      </html>
    </StoreProvider>
  );
}
