import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ChakraProvider } from '@chakra-ui/react';
import { StoreProvider } from '@/redux/store';
import ProtectedPage from '@/routes/protected-routes';
import AuthProvider from '@/routes/auth-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          {/* <Header /> */}
          <ChakraProvider>
            <AppRouterCacheProvider>
              <AuthProvider>
                <ProtectedPage>{children}</ProtectedPage>
              </AuthProvider>
            </AppRouterCacheProvider>
          </ChakraProvider>
          <Footer />
        </body>
      </html>
    </StoreProvider>
  );
}
